#!/usr/bin/python3

# -*- coding: utf-8 -*-
import re
import sys
import eyed3

from eyed3.main import _main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(_main())

